name: Generate Test Artifacts on GitHub-Hosted Runner
on: [push, pull_request]
jobs:
  my-job:
    name: Run MATLAB Tests and Generate Artifacts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        matlab: ['R2020a', 'R2020b']
    env:
      OS: ${{ matrix.os }}
      MATLAB: ${{ matrix.matlab }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: ${{ MATLAB }}
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v1
        with:
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
          source-folder: .
          select-by-folder: tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ./code-coverage
          env_vars: OS,MATLAB
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittests
          name: matlab-helper
          path_to_write_report: ./code-coverage/codecov_report.txt
          verbose: true
